### ISSUE TITLE
好难找到自己哦！

### ISSUE THREAD

**Issue by huangqingchao** [dhso/ha-panel-amap-panel#1]
很棒的地图，按照README的方法，一次就可以了，打开就显示到我的家，无偏移，还有可以定位到我的手机。但是一开始是以我家为中心，而且地图放大级别很大的。如果我离我家很远（我现在是30公里），好难找到我自己哦。官方的貌似打开会把放大级别和位置调到可以看到我和我的家。这属于问题么.....

**Comment by dhso** [comment]
其实这里已经做了自动缩放，但是目标是设定的zone而不是所有的点，建议你在常用地点设置一个zone，比如公司或某个大桥，这样就会好点。
