### ISSUE TITLE
有时缩放地图比例尺不会同步更新

### ISSUE THREAD

**Issue by zslibra** [dhso/ha-panel-amap-panel#2]
您好，发现一个问题是有时缩放地图比例尺不会同步更新。
谢谢

**Comment by zslibra** [comment]
测试以“家”的位置为中心，缩放地图时有时比例尺不会同步更新。
操作如下：在以“家”位置为中心，先将地图放到最大，然后开始缩小，100米的比例尺有两级是一样的（正常的每级缩放比例尺会不一样）。如果拉到其它位置（“家”没有显示在地图上）缩放时比例尺更新又是正常的。
尝试更换firefox, chrome, Edge情况都一样

**Comment by dhso** [comment]
> 测试以“家”的位置为中心，缩放地图时有时比例尺不会同步更新。
> 操作如下：在以“家”位置为中心，先将地图放到最大，然后开始缩小，100米的比例尺有两级是一样的（正常的每级缩放比例尺会不一样）。如果拉到其它位置（“家”没有显示在地图上）缩放时比例尺更新又是正常的。
> 尝试更换firefox, chrome, Edge情况都一样

谢谢你的细心发现，这个其实是高德地图的比例尺bug。按照你说的我去高德地图上看了，也是这样的。我这边是200m的比例尺会显示两次。
https://www.amap.com/
如果高德地图修复了，这边也会对应显示正常。
