### ISSUE TITLE
不能正确显示entity_picture

### ISSUE THREAD

**Issue by zslibra** [dhso/ha-panel-amap-panel#8]
您好，高德地图插件很好用，最近发现一个问题是device tracker的entity_picture不能显示。
我的homeassistant版本是core-2021.3.3，device tracker添加了entity_picture，在homeassistant 自带的map能正常显示entity_picture。
使用高德地图插件，发现在地图上不显示 entity_picture，但地图看上去会自动缩放到合适的大小，只是不显示device tracker。不设置entity_picture能正常的显示首字母的图标device tracker。我设置的entity_picture是192*192大小的png图片。
请问要怎样设置才能正确显示entity_picture？
谢谢

**Comment by zslibra** [comment]
一个比较奇怪的情况，entity_picture不是完全不能显示。是要点一下自带的map，然后再点高德地图插件就能显示出entity_picture了。如果浏览器画面在高德地图插件，按F5刷新，entity_picture会消失不见了，就算多次刷新也不会显示，只能再点一下自带的map，再切换回高德地图插件entity_picture才会重新显示出来。

**Comment by dhso** [comment]
不好意思，现在再试试呢，应该解决了。 @zslibra
